<?php
require_once __DIR__ . '/../config/database.php'; require_login(); $db=(new Database())->getConnection(); $uid=$_SESSION['user_id']; $success=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
$date=$_POST['trade_date']??date('Y-m-d');$asset=trim($_POST['asset']??'');$tf=trim($_POST['timeframe']??'');$setup=trim($_POST['setup']??'');$condition=trim($_POST['market_condition']??'');$entry=$_POST['entry_price']!==''?$_POST['entry_price']:null;$sl=$_POST['stop_loss']!==''?$_POST['stop_loss']:null;$tp=$_POST['take_profit']!==''?$_POST['take_profit']:null;$result=$_POST['result']??'';$rr=$_POST['risk_reward']!==''?$_POST['risk_reward']:0;$reason=trim($_POST['reason']??'');$lesson=trim($_POST['lesson_learned']??'');
if($asset && in_array($result,['Win','Loss','Break Even'],true)){ $q=$db->prepare("INSERT INTO trading_journal(user_id,trade_date,asset,timeframe,setup,market_condition,entry_price,stop_loss,take_profit,result,risk_reward,reason,lesson_learned) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)");$q->execute([$uid,$date,$asset,$tf,$setup,$condition,$entry,$sl,$tp,$result,$rr,$reason,$lesson]);$success="Jurnal berhasil disimpan."; } else $error="Asset dan hasil trade wajib diisi.";}
$q=$db->prepare("SELECT * FROM trading_journal WHERE user_id=? ORDER BY trade_date DESC,id DESC");$q->execute([$uid]);$journals=$q->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Journal · TradingLearn</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="bg-slate-50"><nav class="bg-white border-b"><div class="max-w-6xl mx-auto p-4 flex justify-between"><a class="font-bold text-blue-600" href="dashboard.php">TradingLearn</a><a href="roadmap.php">Roadmap</a></div></nav><main class="max-w-6xl mx-auto p-5 md:p-8"><h1 class="text-3xl font-black">Trading Journal 📓</h1><p class="text-slate-500 mt-2 mb-6">Gunakan jurnal untuk mengevaluasi proses, bukan untuk mengejar jumlah trade.</p>
<?php if($success):?><div class="p-4 mb-4 bg-emerald-50 text-emerald-700 rounded-xl"><?=$success?></div><?php endif;?><?php if($error):?><div class="p-4 mb-4 bg-red-50 text-red-700 rounded-xl"><?=e($error)?></div><?php endif;?>
<form method="post" class="bg-white border rounded-3xl p-6 grid md:grid-cols-3 gap-4"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>">
<?php $fields=[['trade_date','Tanggal','date'],['asset','Asset / Pair','text'],['timeframe','Timeframe','text'],['setup','Setup','text'],['market_condition','Market Condition','text'],['entry_price','Entry','number'],['stop_loss','Stop Loss','number'],['take_profit','Take Profit','number'],['risk_reward','R:R','number']];foreach($fields as $f):?><div><label class="text-sm font-medium"><?=$f[1]?></label><input name="<?=$f[0]?>" type="<?=$f[2]?>" step="any" value="<?=e($f[0]==='trade_date'?date('Y-m-d'):'')?>" class="mt-1 w-full p-3 rounded-xl border"></div><?php endforeach;?>
<div><label class="text-sm font-medium">Result</label><select name="result" class="mt-1 w-full p-3 rounded-xl border"><option>Win</option><option>Loss</option><option>Break Even</option></select></div>
<div class="md:col-span-3"><label class="text-sm font-medium">Alasan / Thesis</label><textarea name="reason" rows="2" class="mt-1 w-full p-3 rounded-xl border"></textarea></div><div class="md:col-span-3"><label class="text-sm font-medium">Lesson Learned</label><textarea name="lesson_learned" rows="2" class="mt-1 w-full p-3 rounded-xl border"></textarea></div>
<button class="md:col-span-3 p-3 bg-blue-600 text-white rounded-xl font-bold">Simpan Jurnal</button></form>
<div class="mt-8 bg-white border rounded-3xl overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-100"><tr><th class="p-4 text-left">Tanggal</th><th class="p-4 text-left">Asset</th><th class="p-4">TF</th><th class="p-4">Result</th><th class="p-4">R:R</th><th class="p-4 text-left">Setup</th></tr></thead><tbody><?php foreach($journals as $j):?><tr class="border-t"><td class="p-4"><?=e($j['trade_date'])?></td><td class="p-4 font-semibold"><?=e($j['asset'])?></td><td class="p-4 text-center"><?=e($j['timeframe'])?></td><td class="p-4 text-center"><?=e($j['result'])?></td><td class="p-4 text-center">1:<?=e($j['risk_reward'])?></td><td class="p-4"><?=e($j['setup'])?></td></tr><?php endforeach;if(!$journals):?><tr><td colspan="6" class="p-6 text-center text-slate-400">Belum ada jurnal.</td></tr><?php endif;?></tbody></table></div>
</main></body></html>
